api_platform:
    title: Hello API Platform
    version: 1.0.0
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
    mapping:
        paths:
            - '%kernel.project_dir%/src/Catalog/Product/Domain/Model'
            - '%kernel.project_dir%/src/Catalog/ProductVariant/Domain/Model'
            - '%kernel.project_dir%/src/Catalog/ProductOption/Domain/Model'
            - '%kernel.project_dir%/src/Catalog/Category/Domain/Model'
            - '%kernel.project_dir%/src/Catalog/Brand/Domain/Model'
