<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260625210517 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE catalog_product_option (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(64) NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_AB8F531977153098 ON catalog_product_option (code)');
        $this->addSql('CREATE TABLE catalog_product_option_value (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(64) NOT NULL, value VARCHAR(255) NOT NULL, option_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_AC32460C77153098 ON catalog_product_option_value (code)');
        $this->addSql('CREATE INDEX IDX_AC32460CA7C41D6F ON catalog_product_option_value (option_id)');
        $this->addSql('ALTER TABLE catalog_product_option_value ADD CONSTRAINT FK_AC32460CA7C41D6F FOREIGN KEY (option_id) REFERENCES catalog_product_option (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE catalog_product_option_value DROP CONSTRAINT FK_AC32460CA7C41D6F');
        $this->addSql('DROP TABLE catalog_product_option');
        $this->addSql('DROP TABLE catalog_product_option_value');
    }
}
