<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260627224252 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE category (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(64) NOT NULL, name VARCHAR(255) NOT NULL, slug VARCHAR(255) NOT NULL, description TEXT DEFAULT NULL, enabled BOOLEAN NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_64C19C177153098 ON category (code)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_64C19C1989D9B62 ON category (slug)');
        $this->addSql('CREATE TABLE catalog_product_variant_option_value (product_variant_id INT NOT NULL, product_option_value_id INT NOT NULL, PRIMARY KEY (product_variant_id, product_option_value_id))');
        $this->addSql('CREATE INDEX IDX_1D44664DA80EF684 ON catalog_product_variant_option_value (product_variant_id)');
        $this->addSql('CREATE INDEX IDX_1D44664DEBDCCF9B ON catalog_product_variant_option_value (product_option_value_id)');
        $this->addSql('ALTER TABLE catalog_product_variant_option_value ADD CONSTRAINT FK_1D44664DA80EF684 FOREIGN KEY (product_variant_id) REFERENCES product_variant (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE catalog_product_variant_option_value ADD CONSTRAINT FK_1D44664DEBDCCF9B FOREIGN KEY (product_option_value_id) REFERENCES catalog_product_option_value (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE product ADD code VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE product ADD category_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE product ADD CONSTRAINT FK_D34A04AD12469DE2 FOREIGN KEY (category_id) REFERENCES category (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_D34A04AD12469DE2 ON product (category_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE catalog_product_variant_option_value DROP CONSTRAINT FK_1D44664DA80EF684');
        $this->addSql('ALTER TABLE catalog_product_variant_option_value DROP CONSTRAINT FK_1D44664DEBDCCF9B');
        $this->addSql('DROP TABLE category');
        $this->addSql('DROP TABLE catalog_product_variant_option_value');
        $this->addSql('ALTER TABLE product DROP CONSTRAINT FK_D34A04AD12469DE2');
        $this->addSql('DROP INDEX IDX_D34A04AD12469DE2');
        $this->addSql('ALTER TABLE product DROP code');
        $this->addSql('ALTER TABLE product DROP category_id');
    }
}
